---
title: "Homework #5"
author: "Nicole R Gorman"
date: "2024-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Question 1:**  
<br>

```{r echo=TRUE, results=TRUE}
#Assign to the variable n_dims a single random integer between 3 and 10. 
n_dims <-sample(3:10,1) #can also write (3:10,size=1)...same result
print(n_dims)

# vector of consecutive integers from 1 to n_dims^2
my_vec <-1:n_dims^2
print(my_vec)

# randomly reshuffle these values
my_vec <- sample(my_vec)
print(my_vec)

# create a square matrix with these elements, print
# making nrow=ndims makes sure that any random number will work
m <- matrix(data=my_vec,nrow=n_dims) 
print(m)

# a function in r to transpose the matrix is by row because the default is bycol, so vector is loaded as a transposed matrix
m_trans <- matrix(data=my_vec,ncol=n_dims,byrow=TRUE)
print(m_trans)

# or use t() which is the matrix transpose function, to do the same thing
tm <- t(m) 
print(tm)

# calculate the sum and the mean of the elements in the first row and then the last row.
row1sum <- sum(m[1,])
row1mean <- mean(m[1,])
print (row1sum)
print (row1mean)

# read about the eigen() function and use it on your matrix
isSym <- isSymmetric(m)
print(isSym)
e <- eigen(m, symmetric=FALSE, only.values = FALSE, EISPACK = FALSE)

# Eigenvectors and eigenvalues can be used to summarize a matrix 
# PCA is built on the concept of Eigenvectors and Eigenvalues
# PCA can be used to condense multidimensional data into two dimensions to try and identify any structure within a data set. 
# An eigen vector is the direction of the line of best fit of the data set, while an eigenvalue is a measure of how the data is spread out on the vector.

# look carefully at the elements of $values and $vectors in the output. What kind of numbers are these?
# A list of the  eigenvectors, with sign indicating direction as well as eigenvalues

# dig in with the typeof() function to figure out their type.
typeof(e)

# if have set your code up properly, you should be able to re-run it and create a matrix of different size because n_dims will change.
n_dims <-sample(3:10,1)
print(n_dims)

my_vec <-1:n_dims^2
print(my_vec)

my_vec <- sample(my_vec)
print(my_vec)
 
m <- matrix(data=my_vec,nrow=n_dims) 
print(m)

m_trans <- matrix(data=my_vec,ncol=n_dims,byrow=TRUE)
print(m_trans)

tm <- t(m) 
print(tm)

row1sum <- sum(m[1,])
row1mean <- mean(m[1,])
print (row1sum)
print (row1mean)

isSym <- isSymmetric(m)
print(isSym)
e <- eigen(m, symmetric=FALSE, only.values = FALSE, EISPACK = FALSE)
typeof(e)

```

## **Question 2:**  <br>
Create a list with the following named elements:

```{r echo=TRUE, results=TRUE}

# my_matrix, which is a 4 x 4 matrix filled with random uniform values
my_matrix<-matrix(rnorm(16),nrow=4,byrow=TRUE)
print(my_matrix)

# my_logical which is a 100-element vector of TRUE or FALSE values. Do this efficiently by setting up a vector of random values and then applying an inequality to it.
my_vec2 <- runif(n=100)
print(my_vec2)
my_logical <- my_vec2 > 0.05
print(my_logical)

# my_letters, which is a 26-element vector of all the lower-case letters in random order

my_letters <- sample(letters)
print(my_letters)

# Generate the list with each item
my_list <-list (matrix(rnorm(16),nrow=4,byrow=TRUE),
               runif(n=100), 
               my_vec2 > 0.05,sample(letters))
str(my_list)
print(my_list)

# I can't get the original vector to not show up in the list. I tried several calls. For example, I tried to use the following, no luck. I will keep trying :)
#my_List <-list (matrix(rnorm(16),echo=TRUE, results=FALSE,nrow=4,
#               byrow=TRUE),runif(n=100), my_vec2 > 0.05,sample(letters))

```

Then, complete the following steps:
```{r echo=TRUE, results=TRUE}
# create a new list, which has the element[2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector.

new_list <- list(my_matrix[[2,2]],my_logical[[2]],my_letters[[2]])
print(new_list)

# use the typeof() function to confirm the underlying data types of each component in this list
typeof(new_list)
typeof(new_list[[1]])
typeof(new_list[[2]])
typeof(new_list[[3]])
typeof(my_matrix)
typeof(my_logical)
typeof(my_letters)
str(new_list)
#I can get each list item to return separate results, but I can't seem to get typeof() to give me all three data types at once. Hmmmm....

#typeof(new_list[[1]],[[2]],[[3]])
# it seems like this should work, but nope!

#combine the underlying elements from the new list into a single atomic vector with the c() function. 

new_matrix <- my_matrix[2,2]
new_logical <- my_logical [2]
new_letters <- my_letters [2]

c_vec <- c(new_matrix, new_logical, new_letters)
print(c_vec)

# Or can also use the unlist function
new_vec <- unlist(new_list)
print(new_vec)

#what is the data type of this vector?
typeof(new_vec)

```

## **Question 3:**  
<br>

Create a data frame with the two variables (= columns) and 26 cases (= rows) below:
```{r echo=TRUE, results=TRUE}
# call the first variable my_unis and fill it with 26 random uniform values from 0 to 10
varA <- 1:26 # number each row, 1-26
my_unis <- sample(1:10, size=26, replace=TRUE)
print(my_unis)
  
# call the second variable my_letters and fill it with 26 capital letters in random order.
my_letters <- sample(LETTERS) # sample function scrambles the letters
print(my_letters)

# for the first variable, use a single line of code in R to select 4 random rows and replace the numerical values in those rows with NA.
dFrame <- data.frame(varA,v=my_unis,x=my_letters) # create a dataframe
head(dFrame)
print(dFrame)
str(dFrame)

# need to figure out how to select 4 random samples, can only replace the fourth value 
my_unis[4] <- NA # contaminate the dataframe
print(my_unis)

### Can I use something like this?
### Syntax: df[ sample(which ( conditions ) ,4), ]

# for the first variable, write a single line of R code to identify which rows have the missing values.
which(!complete.cases(my_unis))

# re-order the entire data frame to arrange the second variable in alphabetical order
### Why won't the data frame print?
dFrame <- dFrame[order(dFrame$x),]
print(dFrame)
head(dFrame)
tail(dFrame)

# calculate the column mean for the first variable.
mean(dFrame[ ,2])
summary(dFrame)

```

