---
title: "Computational Biology"
author: "Nicole R Gorman"
date: "2024-01-25"
output: 
  html_document:
    theme: cerulean
    highlight: tango
    toc: no
    toc_float:
        collapse: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Homeworks

### Homework #1: Github  
+ Click here to find my [github repository](https://github.com/NicoleRGorman).  
+ My user name is NicoleRGorman

### Homework #2: R Markdown 
+ This is a [link](RegularExpressions.html) to another webpage.

### Homework #3: Regular Expressions
+ Please click [here](Homework3.html) to find homework #3.

### Homework #4: Using R, Atomic Vectors
+ Please click [here](Homework4.html) for homework #4.

### Homework #5: Working with Matrices, Lists, and Data Frames
+ Click [here](Homework_5.html) for homework #5!

### Homework #6: Simulating and Fitting Data Distributions
+ Click [here](Homework6.html) for homework #6.

### Homework #7: Creating Fake Data Sets To Explore Hypotheses
+ Click [here](Homework7.html) for homework #7.

### Homework #8: Data manipulations using the dplyr package
+ Click [here](Homework8.html) for homework #8.

### Homework #9: Organizing Code with Structured Programming
+ Click [here](Homework9.html) for homework #9.

### Homework #10: For Loops and Randomization Tests
+ Click [here](Homework10.html) for homework #10.

### Homework #11: Batch Processing
+ Click [here](file:///Users/nicolegorman/Documents/UVM_Coursework/ComputationalBiology/Homework11/Homework11.html) for homework #11. 

+ If that doesn't work, try here:
[Link to Homework11.html](file:///Users/nicolegorman/Documents/UVM_Coursework/ComputationalBiology/Homework11/Homework11.html)

+ And if that doesn't work, try pasting this into your browser: file:///Users/nicolegorman/Documents/UVM_Coursework/ComputationalBiology/Homework11/Homework11.html

### Homework #12: ggplot
+ Click [here](Homework12.html) for homework #12.

# References

