---
title: "Probability_Notes"
author: "Nicole R Gorman"
date: "2024-02-22"
output: html_document
---

Probability distributions in R
Discrete distributions
Poisson
Range: [0,∞
]
Parameters: size = number of events, rate = λ
Interpretation: Distribution of events that occur during a fixed time interval or sampling effort with a constant rate of independent events; resembles normal with large λ
, or exponential with small λ
Binomial
Range: [0, # of trials]
Parameters: size= number of trials; p = probability of positive outcome
Interpretation: Distribution of number of successful independent dichotomous trials, with constant p
Negative Binomial
Range: [0, ∞
]
Parameters: size=number of successes; p = probability of success
Interpretation: Distribution of number of failures in a series of independent Bernouli trials, each with p = probability of a success. Generates a discrete distribution that is more heterogeneous (“overdispersed”) than Poisson
Continuous distributions
Uniform
Range: [min,max]
Parameters: min = minimum boundary; max = maximum boundary
Interpretation: Distribution of a value that is equally likely within a specified range
Normal
Range: [−∞,∞
]
Parameters: mean = central tendency; SD = standard deviation
Interpretation: Symmetric bell-shaped curve with unbounded tails
Gamma Γ
Range: [0,∞
]
Parameters: shape, scale
Interpretation: mean=shape∗scale
, variance=shape∗scale2
; generates a variety of shapes (including normal and exponential) for positive continuous variables
Beta β
Range: [0,1] (can be rescaled to any range by simple multiplication and addition)
Paramters: shape1, shape2
Interpretation: if shape1 and shape 2 are integers, interpret as a coin toss, with shape1 = # of successes + 1, shape2 = # of failures + 1. Gives distribution of value of p, estimated from data, which can range from exponential through uniform through normal (but all are bounded). Setting shape1 and shape2 <1 yields u-shaped distributions.
